name: Build & Release MATLAB Toolbox

on:
  release:
    types: [published]

jobs:  
  release-toolbox:
    if: github.repository == 'TopoToolbox/ttminvoellmy'
    runs-on: ubuntu-latest

    permissions:
      contents: write   # required to update release      
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@a0180c939fb1a28de13f44f7b778b912384ced1f # v 3.0.1
        with:
          release: r2025a
          cache: true
          
      - name: Build toolbox
        uses: matlab-actions/run-build@e6fa4ea64b81a3a277395febd62db266faca1d0c # v 3.1.1
        with:
          tasks: package

      - name: Upload toolbox artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: toolbox
          path: release/ttminvoellmy.mltbx

      - name: Upload toolbox assets
        shell: bash
        run: gh release upload --repo $GITHUB_REPOSITORY $TAG release/ttminvoellmy.mltbx
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
